version: '3.8'

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      API_URL: ${API_URL}
      ENVIRONMENT: docker
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "3004:3004"

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    environment:
      API_URL: http://api:3004
      ENVIRONMENT: docker
    depends_on:
      - api
    volumes:
      - ./scheduler:/app
    restart: unless-stopped

volumes:
  db-data: